server:
  port: 10001
  servlet:
    context-path: /api
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://182.92.205.224/redyu_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: Xhz199838.
  profiles:
    active: dev
  redis:
    host: 182.92.205.224
    port: 6379
    #timeout: 3000
    password: Xhz199838.
  servlet:
    multipart:
      enabled: true
      max-file-size: 1024MB
      max-request-size: 1024MB
      resolve-lazily: true
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    default-enum-type-handler: com.czxy.redyu.handler.PostStatusHandler
## 这里即是配置SQL打印的关键位置，设置日志级别为debug begin
#logging:
#  level:
#    com.czxy.redyu.core: debug
#自定义配置
redyu:
  desk:
    url: http://www.redyu.run #前台url
  ras:
    pub: ${user.home}/ras/ras.pub
    pri: ${user.home}/ras/ras.pri
